# language: java
language: android

jdk:
  - oraclejdk7

script: ./prepare_apk.sh

deploy:
  provider: releases
  api_key: "$mifm_deployment_token"
  file:
    - dist/mifm-4-22_cs.apk
    - dist/mifm-4-22_de.apk
    - dist/mifm-4-22_de_DE.apk
    - dist/mifm-4-22_en.apk
    - dist/mifm-4-22_fr.apk
    - dist/mifm-4-22_pl.apk
    - dist/mifm-4-22_pt.apk
    - dist/mifm-4-22_pt_BR.apk
    - dist/mifm-4-22_pt_PT.apk
    - dist/mifm-4-22_sk.apk
    - dist/mifm-4-22_sr_RS.apk
    - dist/mifm-4-22_tr.apk
    - dist/mifm-4-22_uk.apk
    - dist/mifm-4-22_zh.apk

  skip_cleanup: true
  on:
    tags: true
