# language: java
language: android

jdk:
  - oraclejdk7

script: ./prepare_apk.sh

deploy:
  provider: releases
  api_key: "$mifm_deployment_token"
  file:
    - dist/mifm-1.39_en.apk
    - dist/mifm-1.39_pl.apk
    - dist/mifm-1.39_ru.apk
    - dist/mifm-1.39_sk.apk
  skip_cleanup: true
  on:
    tags: true

